name: bloc_flux
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Brennan Gambling <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  rxdart: ^0.20.0
  meta: ^1.1.7
  built_collection: ^4.1.0
  built_value: 6.3.0

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.1.3
  built_value_generator: 6.3.0
  quiver: ^2.0.1
