name: bloc_flux
description: A reactive flux-like state management library using the BLoC pattern.
version: 0.1.0
homepage: https://github.com/BrennanGambling/bloc_flux/tree/master/bloc_flux
repository: https://github.com/BrennanGambling/bloc_flux
issue_tracker: https://github.com/BrennanGambling/bloc_flux/issues
author: Brennan Gambling <brennan.gambling@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  rxdart: ^0.20.0
  quiver: '>=2.0.0 <3.0.0'
  meta: ^1.1.7
  built_collection: ^4.1.0
  built_value: 6.3.0
  mockito: ^4.0.0

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.1.3
  built_value_generator: 6.3.0
  bloc_flux_testing: ^0.1.0

dependency_overrides:
  bloc_flux_testing:
    path: ../bloc_flux_testing